### ISSUE TITLE
Write SQL to extract NM cancer volume from the tumor registry to export to Cancer InFocus.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#114]
Add to export
--age at diagnosis
--county at diagnosis
--facility
	--decide how to attribute facility

--support mapping to highligh cancer type
	--ask NeuralFrame to manage the mappings

Get approval and add to export
--staging (pathological stage group)

**Comment by PerifanosPrometheus** [comment]
Comprehensive column list:
--age at diagnosis
--countyAtDx
--facility
--tumor site

If possible(need to check for approval):
--staging

**Comment by PerifanosPrometheus** [comment]
Testing completed! we can close.
