### ISSUE TITLE
Create an R script that will create a hemonc_concept_ancestor table that functions like the OHDSI concept_ancestor table.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#129]
I have create a Ruby script that does this but Hemonc.org uses R, so if we want to contribute this the main project, we need to convert it to R.

**Comment by PerifanosPrometheus** [comment]
We actually decided to do this in SQL directly using a recursive CTE. The advantage of utilizing SQL is that we can now incorporate the code into the ETL process and make it easier for research data analysts to use this data.

**Comment by PerifanosPrometheus** [comment]
I completed the development and we are now testing/validating before converting into a database object.

**Comment by PerifanosPrometheus** [comment]
This was completed.
