### ISSUE TITLE
QDSC Project ID 1096 ( Laila Gharzai): EDW Export

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#148]
https://redcap.nubic.northwestern.edu/redcap/redcap_v13.1.37/DataEntry/index.php?pid=1427&page=qdsc_appointment_request&id=1096&event_id=7412&instance=1

**Comment by PerifanosPrometheus** [comment]
PR in progress

**Comment by PerifanosPrometheus** [comment]
Waiting for final approval

**Comment by PerifanosPrometheus** [comment]
Data approved and released. Closing
