### ISSUE TITLE
Convert feasability into NMEDW data export  (Wafik Sedhom) 

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#167]
See prior reserach request: https://jira.fsm.northwestern.edu/browse/RW-4845?jql=text%20~%20%22wafik%22

**Comment by PerifanosPrometheus** [comment]
Created a NM_extract called [RHLCC_leukocytosis_volume]. Need to talk to Mike and figure out cadence of extraction and destination folder.

**Comment by PerifanosPrometheus** [comment]
![image](https://github.com/user-attachments/assets/a6192690-4ecd-442b-92d0-96d959e41bda)

**Comment by PerifanosPrometheus** [comment]
Work on basic variables for now:
everything up to JAK2 V617F, BCR-ABL

**Comment by PerifanosPrometheus** [comment]
Completed
