### ISSUE TITLE
NMEDW Request 5038 (Seth Pollack): Sarcoma patients with specific histologies:

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#169]
- Undifferentiated pleomorphic sarcoma (15 cases) 
- Dedifferentiated Liposarcoma (15 cases)
- Leiomyosarcoma (15 cases)
- Synovial sarcoma (8 cases)
- Desmoplastic small round cell tumors (8 cases)
- Angiosarcoma  (8 cases)
- Malignant peripheral nerve sheath tumors(MPNST) (8 cases)
- Ewing sarcoma (8 cases)
- Osteosarcoma (8 cases)

Pathology accession numbers (to be released to the Pathology Core Facility) to request from the CSRC. Associated clinical data requesting to be released. A detailed data dictionary is available. Cancer History Pathology Surgery Anti-neoplastic Systemic Treatments Radiation Treatments Imaging Exam Reports Disease Status Genomic Results Survival/Death

**Comment by PerifanosPrometheus** [comment]
Report was completed. We are now going forward with the process to ask Pathcore to search for the specimens and provide them to researchers.

**Comment by PerifanosPrometheus** [comment]
https://jira.fsm.northwestern.edu/browse/RW-5245?filter=-1&jql=assignee%20in%20(currentUser())%20order%20by%20updated%20DESC

**Comment by mgurley** [comment]
We want to add the NM hospital to this report to make it easy for PathCore to prioritize NMH cases over non-NMH cases.  Also remove the headers from the report so opening it to Excel is not so annoying.

**Comment by mgurley** [comment]
Based on feedback from Gabriel/Dr. Pollack, we might move to pulling cases from 2021 on to have quicker access.  We need to check synoptic data for this.

**Comment by mgurley** [comment]
2021 counts were provided to study team.  Waiting on feedback to expand date range on report.
