### ISSUE TITLE
Document out how Cancer InFoucs defines cancer type for its incidence and mortality.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#190]
Cancer InFoucs sources its cancer incidence and mortality from https://statecancerprofiles.cancer.gov/.  How does this website define its Cance Type variable?  It must be based on ICDO3 site/histology because it is based on tumor registry data.  But will it align with what we have been planning to use for NM tumor registry volume and NU clinical trial accrual data: https://cancercenters.cancer.gov/GrantsFunding/ICD10

**Comment by Danton6** [comment]
This is documentation provided for the cancer site groupings: https://seer.cancer.gov/siterecode/icdo3_dwhoheme/index.html
