### ISSUE TITLE
Modify Colposcopy report to be one row per event.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#198]
* Include specialty, region, and provider, year of service.
 * Use Prospr list of Colposcopy CPT codes.
 * Add race, ethnicity, and age grouping (at the time of Colposcopy).

**Comment by neelimakatam** [comment]
Should patient ir_id  be included for this report since we are including race and ethnicity? - as there will be multiple rows per patient

**Comment by mgurley** [comment]
we should use the logic we have in the export of race/ethnicity to normalize to race/ethnicity, but patient_ir_id would be good to add to dedup for multiple colposcopies
