### ISSUE TITLE
Can any of the novel items repeat?  Or can each novel item only be collected once.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#203]
Email from Ryan Jacobs 4/24/2024:

The variables will be collected at 3 different time points: once retrospectively in 2023, then two other times (still finalizing times but probably in 3 months and 6 months)

**Comment by PerifanosPrometheus** [comment]
Notes from Meeting:
- Surgery or something like that can have multiple events. 
- They won't have multiple tumor marker dates.
- New items will only be collected once and not multiple times.

**Comment by mgurley** [comment]
None will operationally repeat.
