### ISSUE TITLE
Create a script that can import the standard file format to each institution-specific REDcap project.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#205]
Use R to import into REDcap.  There will need to be routing logic that takes a file from each subfolder in FSMRESFILES and imports it into each institution-specific REDCap project.  This will need to be deployed to FSM anserver.

**Comment by PerifanosPrometheus** [comment]
Discussed with @mgurley. We will be working together on a ruby script to do this.

**Comment by PerifanosPrometheus** [comment]
Michael completed this.
