### ISSUE TITLE
Draft an input file format document that descibes its structure and semantics.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#208]
Include SOP about only including columns that the institution wants to automatically udpate.

**Comment by mgurley** [comment]
@PerifanosPrometheus  Will create a sample from the NM tumor registry to begin as a template.

**Comment by PerifanosPrometheus** [comment]
https://nuwildcat-my.sharepoint.com/:x:/r/personal/mjg994_ads_northwestern_edu/Documents/ilcc/[ExternalImportSOP.xlsx](https://nuwildcat-my.sharepoint.com/:x:/r/personal/mjg994_ads_northwestern_edu/Documents/ilcc/ExternalImportSOP.xlsx?d=wa1e1ecff33a24ed2b2351f432328d1ca&csf=1&web=1&e=5IEDgD)?d=wa1e1ecff33a24ed2b2351f432328d1ca&csf=1&web=1&e=5IEDgD
