### ISSUE TITLE
Validate that the idea of one REDcap project per institution is OK with statistics/ILCC.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#209]
- We are suggesting doing this because we want to lock down read-only access for each institution to the fields that will be manually entered versus the ones that will be uploaded.
- Sun will need a union across the multiple RECap projects with are API key for each to do reporting across all institutions.

**Comment by PerifanosPrometheus** [comment]
Meeting Notes:
Sun thinks this is fine.
