### ISSUE TITLE
Is it OK that NU holds identified data for non-NU sites in its REDCap instance?

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#210]
Even if we segregate REDCap projects to each institution.

**Comment by PerifanosPrometheus** [comment]
Notes from meeting:
- Make sure data user agreement covers holding identified data.
- IRB states deidentified data in the protocol
- Kristina  Need to check IRB and see what it says
- Kristina Need to talk to IRB to figure out language that should go in the IRB, data user agreement.
