### ISSUE TITLE
ILCC Question - How to handle standard NAACCR items not in NM version of tumor registry?

### ISSUE THREAD

**Issue by PerifanosPrometheus** [NU-QDSC/cancer-informatics#222]
Items missing:
- tobaccoUseSmokingStatus - NAACCR Item 344
- rxSummSurgPrimSite2023 - NAACCR Item 1291

**Comment by PerifanosPrometheus** [comment]
Meeting notes:
- Brenna to connect with NM to confirm whether these items are loaded in NM version of tumor registry. They might be on a different name which is making it hard for us to find them.

**Comment by mgurley** [comment]
Duplicated #270
