### ISSUE TITLE
Feasability for Project 2

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#230]
From Denisha:

Numbers of HGSOC from Black versus White Women:
Frozen tumor with corresponding blood (open to whole blood, plasma or serum)
FFPE embedded with corresponding blood (open to whole blood, plasma or serum)

**Comment by neelimakatam** [comment]
I checked the NU-CHERS ovarian database - There is one patient with HGSOC histology but does not have the right specimens.

**Comment by mgurley** [comment]
Neelima and I completed this request.
