### ISSUE TITLE
ILCC Question - What is the cohort population for Northwestern Data to be imported in redcap?

### ISSUE THREAD

**Issue by PerifanosPrometheus** [NU-QDSC/cancer-informatics#233]
We will need to fully define inclusion/exclusion criteria for the set of patients to be exported into Redcap.

- Does the tumor registry/Sun need help pulling patients for the two populations for NM?
- Once an ILCC patient has been entered into NeuralFrame, can NeuralFrame add a field that designates the ILCC cohort patients?

**Comment by PerifanosPrometheus** [comment]
Additional Context:
The patient population will be made up by 50 patients sampled by two populations.
25 patients will be randomly sampled by the first population and 25 patients will be randomly sampled from the second population.

**Comment by PerifanosPrometheus** [comment]
Notes from meeting:
- Brenna will randomly pick the 50 patients (25 group 1 and 25 group 2) for the study directly in Neuralframe.
- Need to better specify histology codes for Non-small cell lung cancer to aid in reproducibility of sampling at other sites.
- Once the patients are picked, how can we flag them so that we can make sure we include them in the report? 
    - Brenna will check with tumor registry if they can add a field that is something like 'ILCC selected'.

**Comment by mgurley** [comment]
See #269 for NM implementation.
