### ISSUE TITLE
Compare the NIH and NCI cancer mapping namespaces to see how much the diverge.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#241]

**Comment by PerifanosPrometheus** [comment]
[NCI mapping](https://cancercenters.cancer.gov/funding-policies/icd-10)
[NIH mapping](https://seer.cancer.gov/siterecode/icdo3_dwhoheme/index.html)

**Comment by PerifanosPrometheus** [comment]
Performed some comparison, and it quickly became evident that the mappings are different enough to justify loading NIH as an additional mapping and switch to it.

The main differences are related to the fact that NIH mappings are a lot more granular and in the NCI mapping certain sites are "rolled up" differently than in NIH. 

Here are some notable examples, 'Other Digestive Organ' in NCI contains C260 which instead in NIH is assigned as a tumor of 'Large Intestine,NOS'. At the same time, NIH uses C488 for 'Other Digestive Organ' and NCI instead groups it under 'Soft Tissue' tumors. There is enough other such examples to justify switching to the new mapping.

**Comment by PerifanosPrometheus** [comment]
We will be maintaining both mappings.
