### ISSUE TITLE
Validate that all the REDCap/Import SOP fields that need to have possible values have possible values.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#275]
At least these:

ajccTnmClinT
ajccTnmClinN
ajccTnmClinM
ajccTnmPathT
ajccTnmPathN
ajccTnmPathM
ajccTnmClinStageGroup
ajccTnmPathStageGroup
ajccTnmPostTherapyClinT
ajccTnmPostTherapyClinN
ajccTnmPostTherapyClinM
ajccTnmPostTherapyClinStageGrp
ajccTnmPostTherapyT
ajccTnmPostTherapyN
ajccTnmPostTherapyM
ajccTnmPostTherapyStageGroup

rxSummSurgPrimSite
rxSummSurgPrimSite2023

**Comment by PerifanosPrometheus** [comment]
I queried the tumor registry for all the possible T,N,M values and I realized that the possible values for those fields are dependent upon the diagnosis date. This is because depending on the diagnosis date, there was a different version of the ajcc staging with different values. Since the population is limited to patients diagnosed in 2023, I propose simply provide as possible value the ones provided by the version that was active during such time.

**Comment by PerifanosPrometheus** [comment]
### **rxSummSurgPrimSite**
No longer needed
### **rxSummSurgPrimSite2023**
List of codes with names:
 
IF THE DIAGNOSIS DATE IS IN 2023:
| surgery_code | surgery_term |
| ---- | ---- |
| A000| None; no surgery of primary site; autopsy ONLY|
| A190| Local tumor destruction or excision, NOS|
| A150| Local tumor destruction, NOS|
| A120| Laser ablation or cryosurgery|
| A130| Electrocautery; fulguration (includes use of hot forceps for tumor destruction)[SEER Note: Assign code A150 for radiofrequency ablation (RFA)]|
| A200| Excision or resection of less than one lobe, NOS|
| A230| Excision, NOS|
| A240| Laser excision|
| A250| Bronchial sleeve resection ONLY|
| A210| Wedge resection|
| A220| Segmental resection, including lingulectomy|
| A300| Resection of [at least one] lobe or bilobectomy, but less than the whole lung (partial pneumonectomy, NOS)[SEER Note: Assign code A300 when lymph node dissection is not performed, but lymph nodes are obtained as part of the lobectomy specimen]|
| A330| Lobectomy WITH mediastinal lymph node dissection|
| A450| Lobectomy or bilobectomy extended, NOS|
| A460| Lobectomy or bilobectomy extended WITH chest wall|
| A470| Lobectomy or bilobectomy extended WITH pericardium|
| A480| Lobectomy or bilobectomy extended WITH diaphragm|
| A550| Pneumonectomy, NOS[SEER Note:  Code A550 includes complete pneumonectomy, sleeve pneumonectomy, standard pneumonectomy, total pneumonectomy, resection of whole lung.]|
| A560| Pneumonectomy WITH mediastinal lymph node dissection (radical pneumonectomy)|
| A650| Extended pneumonectomy|
| A660| Extended pneumonectomy plus pleura or diaphragm|
| A700| Extended radical pneumonectomy[SEER Note:  An extended radical pneumonectomy is a radical pneumonectomy (including removal of mediastinal nodes) and the removal of other tissues or nodes.]|
| A800| Resection of lung, NOS|
| A900| Surgery, NOS|
| A990| Unknown if surgery performed; death certificate ONLY|
       
IF THE DIAGNOSIS DATE IS IN 2024:
| surgery_code  | surgery_term  |
| ----  | ----  |
| B000 | None; no surgery of primary site; autopsy ONLY |
| B150 | Local tumor destruction, NOS |
| B120 | Laser ablation or cryosurgery |
| B130 | Electrocautery; fulguration (includes use of hot forceps for tumor destruction)[SEER Note: Assign code B150 for radiofrequency ablation (RFA)] |
| B190 | Local tumor destruction or excision, NOS |
| B200 | Excision or resection of less than one lobe, NOS |
| B210 | Wedge resection |
| B220 | Segmental resection, including lingulectomy |
| B230 | Excision, NOS |
| B240 | Laser excision |
| B250 | Bronchial sleeve resection ONLY |
| B300 | Resection of lobe or bilobectomy, but less than the whole lung (partial pneumonectomy, NOS) |
| B320 | Bronchial sleeve lobectomy/bilobectomy |
| B330 | Lobectomy WITH mediastinal lymph node dissection[SEER Note: Assign code B300 when lymph node dissection is not performed, but lymph nodes are obtained as part of the lobectomy specimen] |
| B450 | Lobe or bilobectomy extended, NOS |
| B460 | Lobe or bilobectomy extended WITH chest wall |
| B470 | Lobe or bilobectomy extended WITH pericardium |
| B480 | Lobe or bilobectomy extended WITH diaphragm |
| B550 | Pneumonectomy, NOS[SEER Note:  Code B550 includes complete pneumonectomy, sleeve pneumonectomy, standard pneumonectomy, total pneumonectomy, resection of whole lung.] |
| B560 | Pneumonectomy WITH mediastinal lymph node dissection (radical pneumonectomy) |
| B650 | Extended pneumonectomy, NOS |
| B660 | Extended pneumonectomy plus pleura or diaphragm |
| B800 | Resection of lung, NOS |
| B900 | Surgery, NOS |
| B990 | Unknown if surgery performed; death certificate ONLY |

**Comment by PerifanosPrometheus** [comment]
Here is a simple list to copy and paste in redcap:
IF THE DIAGNOSIS DATE IS IN 2023:
A000
A190
A150
A120
A130
A200
A230
A240
A250
A210
A220
A300
A330
A450
A460
A470
A480
A550
A560
A650
A660
A700
A800
A900
A990

IF THE DIAGNOSIS DATE IS IN 2024:
B000
B150
B120
B130
B190
B200
B210
B220
B230
B240
B250
B300
B320
B330
B450
B460
B470
B480
B550
B560
B650
B660
B800
B900
B990
