### ISSUE TITLE
Can we handle the semantics of different surgery codes at analysis time and not within REDCap?

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#276]
NAACCR has a very bad habit of changing the meaning of codes based on year and or anatomic site.  This would be very difficult to handle in REDCap.  Can we just store the codes in REDCap and leave the semantics to analysis time?
https://www.naaccr.org/crosswalks-interoperability/

**Comment by mgurley** [comment]
We can remove 1290 because it is for 2022 cases and before.

**Comment by PerifanosPrometheus** [comment]
Yes, Sun will handle this.

Here are the two crosswalk files needed to map codes:
[RX-Summ-Surg-Prim-Site-2024-Tables.xlsx (live.com)](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.naaccr.org%2Fwp-content%2Fuploads%2F2023%2F10%2FRX-Summ-Surg-Prim-Site-2024-Tables.xlsx&wdOrigin=BROWSELINK) - diagnosis dates in 2024 and afterwards
[RX-Summ-Surg-Prim-Site-2023-Tables.xlsx (live.com)](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.naaccr.org%2Fwp-content%2Fuploads%2F2023%2F02%2FRX-Summ-Surg-Prim-Site-2023-Tables.xlsx&wdOrigin=BROWSELINK) - diagnosis dates in 2023 only
