### ISSUE TITLE
Map NOTIS disease sites to ICD-O-3 codes in accordance with the NIH cancer type mappings.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#281]
See here:  https://seer.cancer.gov/siterecode/icdo3_dwhoheme/index.html

Hand off to NOTIS team to implement as new namespace mapping.

**Comment by PerifanosPrometheus** [comment]
Mapping was transcribed in [this file](https://github.com/user-attachments/files/15841852/nih_cancer_sites_mapping_table.csv)

**Comment by mgurley** [comment]
Needs to be reviewed.

**Comment by Danton6** [comment]
Duplicated Ticket.
