### ISSUE TITLE
Pull SMRCA variant subtype 4a, alive, Pathology report or Gurardant report, Date: 2020-present

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#311]
Request from Genesis:

Hi,

I met with Dr. Patel to give an update on NU 23L01 recruitment progress earlier this afternoon. 

An action item from the meeting was to pull data for patients with the SMARCA mutation subtype 4a using the EDW.

Since we already have the [Lung Bio-repository Recruitment - Upcoming outpatient and Surgery appointments - Version 2 with NGS variants](https://edw.nm.org/portal/#) EDW version a new column can be added for the SMARCA4 variant.

Request:
Pull SMRCA variant subtype 4a, alive, Pathology report or Gurardant report, Date: 2020-present

I attached a preclinical presentation that included information on the SMARCA variant.

Let me know if you have any questions. We can discuss more if we meet later this week.

[Uploading SMARCA_TPD Summit_TR4 Koichi Ito (1).pdf…]()

**Comment by neelimakatam** [comment]
Deployed the report on 07/18/24
