### ISSUE TITLE
Map NM Tumor volume to reference categories in Cancer inFocus

### ISSUE THREAD

**Issue by Danton6** [NU-QDSC/cancer-informatics#318]
Sites grouped by: https://seer.cancer.gov/siterecode/icdo3_2023_expanded/ maybe?
Daniel will verify SEER mapping used in reference data,

**Comment by Danton6** [comment]
Todd got back to me, https://training.seer.cancer.gov/head-neck/abstract-code-stage/codes.html - is used for Head and Neck site groupings. The Site Recode ICD-O-3/WHO 2008 is used for everything else and https://www.cdc.gov/united-states-cancer-statistics/public-use/definitions-risk-factor-associated-cancers.html is used for the new risk factor associated cancers.

**Comment by PerifanosPrometheus** [comment]
Implemented all mappings except for head & neck. Will complete tomorrow and close the ticket.

**Comment by PerifanosPrometheus** [comment]
@Danton6 do you also want your datafeed to be updated so that it only uses the reference data disease sites?

**Comment by PerifanosPrometheus** [comment]
Because head and neck sites can be grouped under two of the reference data grouping, we will need to create multiple column groupings and figure out how to incorporate in the powerBI report.

**Comment by Danton6** [comment]
Yeah let's just make it cleaner and have it only at the reference data disease sites. We can meet to workout the Head and neck sites. Do you have anytime tomorrow or Friday?

**Comment by PerifanosPrometheus** [comment]
@Danton6 apologies for the delay in response! 

I unfortunately, do not get github notifications on my work email so next time feel free to send me an email.

I am going to send an invite based upon our availabilities in the next few days.

**Comment by PerifanosPrometheus** [comment]
For now, we will use Head & Neck and not use the more detailed groupings.

**Comment by PerifanosPrometheus** [comment]
Reopening to track Implementation in Notis

**Comment by mgurley** [comment]
Ready to be deployed to production.

**Comment by mgurley** [comment]
This is done.  Giorgio will hand off report version before next monthly extract.
