### ISSUE TITLE
Fix the 'EGFR Mutational Analysis Results' answer typo accross all REDCap projects.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#321]
Is this:
4, 3 - Abnormal (mutated)/detected, NOS, exon(s) not specified

Should be this:

3, 3 - Abnormal (mutated)/detected, NOS, exon(s) not specified

**Comment by neelimakatam** [comment]
Fixed the typo in affiliate site REDCap projects
