### ISSUE TITLE
Oncoset Data Questions for collaboration with Pharma

### ISSUE THREAD

**Issue by PerifanosPrometheus** [NU-QDSC/cancer-informatics#326]
A pharma company is interested in answering some questions about the capabilities of our oncoset data.

Here are the questions they have with associated deliverables:
1) Can we get total number of patients in oncoset? deliverable: provide count of patients in oncoset
2) Can we get total number of patients in oncoset by Stage group – 1,2? deliverable: deliver such counts
3) Can we get total number of patients in oncoset by Diseases – breast, lung, gyn onc? deliverable: deliver such counts by obtaining icd-o-3 sites from tumor registry and mapping them to seer disease sites(https://seer.cancer.gov/siterecode/icdo3_dwhoheme/index.html)
4) Can we get counts for specific biomarkers of patients within the dataset?  (specificity) requestor wanted counts for all biomarkers, we pushed back and asked for specific list of biomarkers they are interested in and we can then calculate the counts. Requestor will follow-up. Check in with them on 7/31.
5) Biomarker indication - see 4)
6) Prevalence of biomarkers - see 4)
7) Is there any unique attribute about our oncoset dataset(think of datapoints uniquely captured by the dataset etc.) - deliverable: follow-up with response and provide either sample report or template containing all the fields that are fed back to epic in the oncoset pdf or all the fields in oncoset. 
8) Treatment decisions/outcomes - said we can only provide alive/dead status but cannot provide whether the cancer was fully cured/in remission easily and probably better for this datafeed to extract that via chart review.
9) Tempus/Guardant/Foundation/Internal  - confirmation that we are capturing this data. no deliverable/follow-up needed.
- we have this data available with caveat. Tempus and guardant up to june last year due to data issues.
- guardant pushes into epic and we have access to that.
- NGS data available in data warehouse

Timeline for 1),2),3)7) should be within the next two weeks as that's when they would like to have all this data compiled.

For biomarkers, we will likely need to reassess after a list is provided to us.

**Comment by PerifanosPrometheus** [comment]
@neelimakatam  and I produced counts for 1,2,3,9 and will be delivering it tomorrow.

**Comment by mgurley** [comment]
We will take the top 3 or 4 Oncoset disease sites and attempt to create biomarker data sets based on tumor registry/synoptic data.

**Comment by PerifanosPrometheus** [comment]
Completed
