### ISSUE TITLE
Address request from Melissa Simon on Triple Negative Breast Cancer and the catchment area.  At the Census Tract level.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#330]
Refinement of #240.  @Danton6  will clarify with Dr. Simon if applying the merging logic will be acceptable.  If so, @PerifanosPrometheus  will geocode the population and add it to extract.

**Comment by Danton6** [comment]
Dr. Feinglass confirmed they would like the patients geocoded and mapped. I will be using the merging algorithm and blurring counts to create de-identified maps.

**Comment by PerifanosPrometheus** [comment]
Completed
