### ISSUE TITLE
Create Documentation for NOTIS Oncology Code Namespaces

### ISSUE THREAD

**Issue by dgourd** [NU-QDSC/cancer-informatics#339]
Created [the intial page of the wiki](https://github.com/NU-QDSC/cancer-informatics/wiki/Namespaces-for-NOTIS-Oncology-Codes)

**Comment by dgourd** [comment]
@PerifanosPrometheus and @fanglinnw, can you take a look and make any corrections and add missing information?

**Comment by fanglinnw** [comment]
> @PerifanosPrometheus and @fanglinnw, can you take a look, make any corrections, and add missing information?

I uploaded additional original mapping spreadsheet and specified which column is used for the mapping. Otherwise it looks good to me.
