### ISSUE TITLE
QDSC 1438: DRUG REC-4881-221 -  STU00221007 - A Phase 2, Open Label Study of REC-4881 in Participants with Unresectable Locally Advanced or Metastatic Cancer with AXIN1 or APC Mutation

### ISSUE THREAD

**Issue by neelimakatam** [NU-QDSC/cancer-informatics#342]
https://redcap.nubic.northwestern.edu/redcap/redcap_v14.0.15/DataEntry/index.php?pid=1427&page=qdsc_appointment_request&id=1438&event_id=7412&instance=1

Genomic result vendor
Genomic result date
Genomic result
AXIN1 mutation
APC mutation
RAS/RAF mutation for colorectal cancer
Metastatic cancer type
Metastatic cancer diagnosis date
Patient first name
Patient last name
Patient NMHC mrn

**Comment by neelimakatam** [comment]
This is DS approved automatically in the portal as this IRB was previously approved for a de-identified images request. Should we resubmit for DS approval for this recruitment report?

**Comment by mgurley** [comment]
Data was delivered 8/26/2024
