### ISSUE TITLE
number of patients who received immunotherapy

### ISSUE THREAD

**Issue by PerifanosPrometheus** [NU-QDSC/cancer-informatics#347]
https://jira.fsm.northwestern.edu/browse/RW-5488

**Comment by mgurley** [comment]
Hi Giorgio,

I am wondering if you can query additional data for this request. Built on the cohort of immunotherapy data I requested last time, can you also identify endocrine diseases based on ICD codes and corresponding medication and lab values (see list below)?  With these data, I plan to generate some summary statistics as preliminary data for R01 resubmission. I have not decided how to summarize the data. At this point, I am just wondering if there are med and lab data in our EDW?

Thanks,
Lili




ICD 9/10 (Endocrine disease, no type I diabetes ) (no code before ICI, date >ICI)
Hypothyroidism: E03; 244
Hyperthyroidism: E05; 242
Thyroiditis : E06; 245
Adrenal Insufficiency: E27; 255
Hypophysitis: E23
medication
Synthroid, levothyroxine, Lovoxyl,Armour, Thyrolar, Liotrix, Cytomel, Liothyronine Sodium, Unithroid, L-Thyroxin, Levo-T, Levoxyl, Novothyrox, Levothroid, Levolet, and Triostat, hydrocortisone, dexamethasone, prednisone, glucocorticoids, methimazole or Propylthiouracil
3. abnormal lab values 
-TSH and T4/T3 for hypo, hyper, adrenal insufficiency, hypothysitis
TSH (Thyroid Stimulating Hormone):LOINC: 3016-3
Free T4 (Thyroxine, Free):LOINC: 3024-7
Total T4 (Thyroxine, Total):LOINC: 3026-2
Free T3 (Triiodothyronine, Free):LOINC: 3052-2
Total T3 (Triiodothyronine, Total):LOINC: 3054-8
cortisol and ACTH for Adrenal insufficiency and hypothysitis
Cortisol: LOINC: 2143-6 (serum or plasma)
ACTH (Adrenocorticotropic Hormone):LOINC: 2141-0

**Comment by PerifanosPrometheus** [comment]
Completed
