### ISSUE TITLE
Determine if we can programatically identify patients that have had a Caris genomic test ordered.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#52]

**Comment by PerifanosPrometheus** [comment]
- Genomic result being pulled from 3 different vendors
- Manual process right now to grab results from vendors and pulling in database
- Legal agreements
   - Only covered a subset of patients
   - Process of convincing NM to move data
- Additional want to bring data from Caris(Vendor)
  - Need to give them list of "caris patients" defined as patients having had caris test ordered to them.
  - No orders in the medical record
  - Look in EMR for Caris orders
    - Looks like there is no order at all

**Comment by PerifanosPrometheus** [comment]
Cannot identify such patients programmatically based upon EMR data.
