### ISSUE TITLE
Operationalize CIFTools pulling new data and saving to a shared location.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#54]
We want to deploy the CIFTools python application to the NOTIS staging/production servers and schedule it to pull a fresh catchment area reference data set and save it to a shared location on FSMResfiles .

**Comment by fanglinnw** [comment]
@mgurley where can I find the path to the shared FSMResFile location. I'm not sure if there's already a request to mount that location to NOTIS server. If not, I can submit a ticket to FSM IT.

**Comment by mgurley** [comment]
> @mgurley where can I find the path to the shared FSMResFile location? I'm not sure if there's already a request to mount that location to NOTIS server. If not, I can submit a ticket to FSM IT.

See path here https://github.com/NU-QDSC/cancer-informatics/issues/55
You should have access.  I have not submitted a ticket to FSM IT to mount this folder to the NOTIS server.  We don't want to clober the /mnt/notis folder already there.

**Comment by fanglinnw** [comment]
R script deployed to NOTIS production server at `/var/www/apps/CIFTools`.
It's scheduled to run daily and the downloaded files are stored in server path`/mnt/ciftools/current`, which is mounted for FSMResFile location at:
`fsmresfiles.fsm.northwestern.edu/fsmresfiles/PrevMed/Projects/QDSC/Projects/10 COE/CIFTools`
