### ISSUE TITLE
Create export of accrual data and export to COE FSMRESFILES folder on monthly basis.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#70]
smb://fsmresfiles.fsm.northwestern.edu/fsmresfiles/PrevMed/Projects/QDSC/Projects/10 COE/CIFTools/accural

**Comment by PerifanosPrometheus** [comment]
Export was created and I have set up a meeting with Daniel and Michael to define details surrounding data delivery to the Cancer In Focus application. 

Reason being that to move data via go-anywhere we need to provide a really specific request to FSM before they can start working on it.

**Comment by PerifanosPrometheus** [comment]
Go Anywhere job and extract scheduled.
